import 'core-js/modules/es.array.from.js'
import 'core-js/modules/es.promise.js'
import 'core-js/modules/es.array.includes.js'
import 'core-js/modules/es.array.fill.js'
import 'whatwg-fetch'
export * from './index'
