name: npm-publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    if: github.repository == 'zhensherlock/watermark-js-plus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install Package
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Pack Package
        run: npm pack

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v7
        with:
          name: npm-package
          path: watermark-js-plus-*.tgz

  publish:
    if: github.repository == 'zhensherlock/watermark-js-plus'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Package Artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: .

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Publish NPM Package
        run: npm publish *.tgz --provenance --access public
